# KernelView Collector
FROM golang:1.22-bookworm AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o kernelview-collector ./cmd/collector/

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /build/kernelview-collector /usr/local/bin/kernelview-collector
USER 1000:1000
ENTRYPOINT ["/usr/local/bin/kernelview-collector"]
